apiVersion: v1
kind: Service
metadata:
  name: external-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
  labels:
    k8s-app: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    k8s-app: enternal-dns
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
  labels:
    k8s-app: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    k8s-app: enternal-dns
