apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  replicas: 4
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: fabxc/instrumented_app
        ports:
        - name: backend
          containerPort: 8080
