apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example
  labels:
    team: backend-team
spec:
  selector:
    matchLabels:
      app: example
  endpoints:    
  - port: backend