apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: nginx-exp
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
