apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-monitoring
  labels:
    app: nginx-monitoring
spec:
  selector:
    matchLabels:
      app: nginx-monitoring
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-monitoring
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf