apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  labels:
    team: nginx-otus
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: nginx