apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: elcovstas/k8s-intro-web:0.0.1
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        add:
        - SYS_PTRACE
    volumeMounts:
    - name: app
      mountPath: "/app"
  initContainers:
  - name: install
    image: busybox:latest
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}  
