image: kibana
imageTag: 8.10.3

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

ingress:
  enabled: true
  annotations: []
    #kubernetes.io/ingress.class: nginx
  hosts:
    - host: kibana.158.160.81.234.nip.io
      paths:
        - path: /
